#!/bin/bash

MINIFIER="java -jar $HOME/bin/yuicompressor-2.4.6.jar"

cd 'js'
$MINIFIER 'core.dev.js' >> 'editor.js'
cat fields/*.js | $MINIFIER --type 'js' >> 'editor.js'

cd '../css'
$MINIFIER 'editor.dev.css' > 'editor.css'
