#!/bin/bash

MINIFIER="java -jar $HOME/bin/yuicompressor-2.4.6.jar"

cd 'js'
cat core.co fields/*.co | coco -cs | $MINIFIER --type 'js' > 'editor.js'

cd '../css'
$MINIFIER 'editor.dev.css' > 'editor.css'
